name: E2E Tests

on:
  workflow_dispatch: 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          browser: chrome
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos

    

