name: E2E Tests

on:
  workflow_dispatch:
     inputs:
       base_url:
         description: 'Escolha o ambiente para os testes(local,homolog,production)'
         required: true
         default: 'http://localhost:3000'
       browser:
          description: 'Escolha o navegador para os testes'
          required: true
          default: 'chrome'
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Cypress run
        uses: cypress-io/github-action@v7
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}
        with:
          start: npm start
          browser: ${{ github.event.inputs.browser }}
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos

    

